apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          imagePullPolicy: Always
          image: ankhtepot/kub-demo-fe:4
          env:
            - name: AUTH_ADRESS
              #              value: "10.106.94.166"
              value: "auth-service.default"