apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template: # always is pod so no need for "kind:"
    metadata:
      labels:
        app: second-app # optional form of both name (app) and value (second-app)
    spec:
      containers:
        - name: second-node
          image: ankhtepot/kub-first-app:latest # or :latest or next line
          imagePullPolicy: Always # : Never
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 5